# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Keld Jørgensen
description: "En data-dreven Data Scientist med store analytiske og kvalitative erfaringer og i besiddelse af en Cand.Scient i Matematik og datalogi. Jeg finder det spændende at være med til at gøre en forretning mere datadreven ved hjælp af at kombinere data og forretningsgange. Jeg har store programmeringserfaringer og er i stand til at nørde med komplekse prædiktive modeller og jonglere rundt med machine-learning algoritmer, og er samtidig i stand til at kommunikere disse ud til resten af virksomheden i et let og forståeligt sprog. "
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Aalborg, Danmark"
resume_url: /docs/blah.docx
avatar_image: /img/keldtst.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/keldjorgensen/" # Add your linkedln handle
github: "https://github.com/Keld-j/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
